openapi: 3.0.0
info:
  title: Licensing Deal Profile API
  version: 1.0.0
  description: Fetch and structure data for stage-gated licensing ROI analysis using ClinicalTrials.gov and SEC filing text.

paths:
  /assemble_deal_profile:
    post:
      operationId: assembleDealProfile
      summary: Combine ClinicalTrials.gov API data and SEC disclosure text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nct_id:
                  type: string
                  example: NCT04583969
                sec_text:
                  type: string
                  example: >
                    This agreement includes a $100 million upfront payment, up to $230 million in milestones...
                sec_url:
                  type: string
                  example: https://www.sec.gov/Archives/edgar/data/0001234567/000123456724000012/ex-10_1.htm
      responses:
        '200':
          description: Structured licensing deal profile
          content:
            application/json:
              schema:
                type: object
